#!/bin/bash
#
# Usaeg :
#   1. echo 'source ~/.myshellrc' > .bashrc
#   2. cp .myshellrc ~/ 
#   3. restart to take effects
#

# Set timezone for current user
export TZ='Asia/Shanghai'

export CHEATCOLORS=true

export EDITOR=vim
# alias can use sudo 
alias sudo='sudo '

# tmux enable 256 color
alias tmux='tmux -2'

#alias ls='ls -G'

# Setup jekyll local server quickly
#alias ifmicro='cd ~/synced_folder/WorkSpace/source-hub && jekyll serve --watch -H 0.0.0.0 ; cd -'
#alias ifmicro-drafts='cd ~/synced_folder/WorkSpace/source-hub && jekyll serve --watch -H 0.0.0.0 --drafts ; cd -'

#
# Build go compile envionment
#
# you must specify GOROOT if you specify istallaition directory
export GOROOT=/usr/local/go
export PATH=$PATH:$GOROOT/bin
# Go Project Work Directory
export GOPATH=$HOME/shared_folder/go
# add Go/bin to PATh
export PATH=$PATH:${GOPATH//://bin:}/bin
# ignore 'net/http' test when build go
export DISABLE_NET_TESTSm=1

#
# layer-vim
# export LAYERVIM_LAYERS_PATH=$HOME/.vim/layers
# export LAYERVIM_LAYERS_REPO_URI='https://github.com/MwumLi/ifmicro-layers.git'

#
# Some configuration for node and npm
#
# use taobao npm 
# Reference : http://npm.taobao.org/
alias cnpm="npm --registry=https://registry.npm.taobao.org \
    --cache=$HOME/.npm/.cache/cnpm \
    --disturl=https://npm.taobao.org/dist \
    --userconfig=$HOME/.cnpmrc"


#
# Some configurations for zsh when next login
#

if [[ $SHELL == *zsh ]];then
	alias -s md=vim;
    # forbit history share in more teriminal
    unsetopt sharehistory
    unsetopt inc_append_history

fi

#
# Man page -- highlight
#
export LESS_TERMCAP_mb=$'\E[01;31m'       # begin blinking
export LESS_TERMCAP_md=$'\E[01;38;5;74m'  # begin bold
export LESS_TERMCAP_me=$'\E[0m'           # end mode
export LESS_TERMCAP_se=$'\E[0m'           # end standout-mode
export LESS_TERMCAP_so=$'\E[38;5;246m'    # begin standout-mode - info box
export LESS_TERMCAP_ue=$'\E[0m'           # end underline
export LESS_TERMCAP_us=$'\E[04;38;5;146m' # begin underline

vman() {
    /usr/bin/man $* | \
        col -b | \
        iconv -c | \
        vim -R -c 'set ft=man nomod nolist' -
}

function laravel() {
  ( cd /Users/Luo/WorkSpace/vagrant/laravel && vagrant $* )
}

## proxy
enable_proxy() {
  # 使用你的真实代理地址替换
  # proxy=http://x.x.x.x:8080

  if [ -n $1 ]
  then
    proxy=$1
  fi

  export http_proxy=$proxy
  export https_proxy=$proxy
  export all_proxy=$proxy
  curl ip.gs
}

disable_proxy() {

  unset http_proxy
  unset https_proxy
  unset all_proxy
  curl ip.gs
}

up_proxy() {
  ssh -o ServerAliveInterval=60 -D 127.0.0.1:7070 proxy
}

#
# To do list :
# 1. set  Workspace path for vagrant
